version: '3' # versão mais atual
services: # yml - hierarquia por identação
  db:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes:
      - ./backend:/backend #pra que eu consiga ler app.js e package.json - entro no ./backend e mapeio para /backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm  i --no-bin-links && node app" # sem ser windows pode ser -> bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80